# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 18:51
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='email',
            managers=[
                ('emailValidate', django.db.models.manager.Manager()),
            ],
        ),
    ]
